version: 2
updates:
  # 1️⃣ Dependencies for npm (frontend)
  - package-ecosystem: "npm"
    directory: "/" # Root directory where package.json is located
    schedule:
      interval: "weekly" # Check for updates once a week
      day: "sunday"
      time: "06:00" # UTC time (change as needed)
    open-pull-requests-limit: 5 # Limit concurrent PRs
    labels:
      - "dependencies"
      - "npm"
    ignore:
      - dependency-name: "react"
        versions: [ "<18.0.0" ] # Ignore outdated React versions
    groups:
      minor-updates:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch" # Group minor & patch updates in one PR

  # 2️⃣ Dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "ci/cd"
      - "dependencies"

  # 3️⃣ Dependencies for Docker (if applicable)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "dependencies"
