version: "3.8"
services:
  db:
    image: postgis/postgis:16-3.4
    env_file: .env.development
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    image: ${DOCKERHUB_USER}/entrelibros-backend:dev
    env_file: .env.development
    ports:
      - "4000:4000"
    depends_on:
      - db
  frontend:
    image: ${DOCKERHUB_USER}/entrelibros-frontend:dev
    env_file: .env.development
    ports:
      - "3000:3000"
    depends_on:
      - backend
volumes:
  db_data:
