ALTER TABLE book_corners
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS neighborhood TEXT,
  ADD COLUMN IF NOT EXISTS street TEXT,
  ADD COLUMN IF NOT EXISTS street_number TEXT,
  ADD COLUMN IF NOT EXISTS unit TEXT,
  ADD COLUMN IF NOT EXISTS postal_code TEXT,
  ADD COLUMN IF NOT EXISTS reference_point_label TEXT,
  ADD COLUMN IF NOT EXISTS schedule TEXT,
  ADD COLUMN IF NOT EXISTS rules TEXT,
  ADD COLUMN IF NOT EXISTS is_open_now BOOLEAN,
  ADD COLUMN IF NOT EXISTS themes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS scope TEXT,
  ADD COLUMN IF NOT EXISTS host_alias TEXT,
  ADD COLUMN IF NOT EXISTS internal_contact TEXT,
  ADD COLUMN IF NOT EXISTS visibility_preference TEXT,
  ADD COLUMN IF NOT EXISTS consent BOOLEAN,
  ADD COLUMN IF NOT EXISTS status TEXT;

CREATE TABLE IF NOT EXISTS book_corner_photos (
  id SERIAL PRIMARY KEY,
  corner_id INTEGER NOT NULL REFERENCES book_corners(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  is_primary BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS book_corner_photos_corner_id_idx
  ON book_corner_photos(corner_id);
