ALTER TABLE book_listings
  ADD COLUMN IF NOT EXISTS content_consent BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS image_consent BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS rules_consent BOOLEAN NOT NULL DEFAULT true;
