import type {
  CommunityCorner,
  CommunityListing,
  CommunityUserProfile,
  CommunitySwap,
} from './communityStats.js';

// TODO: Replace this mock dataset with real persistence-backed queries once the
// community module is wired to the production database.
export const COMMUNITY_REFERENCE_DATE = new Date('2025-11-01T12:00:00.000Z');

export const COMMUNITY_USERS: readonly CommunityUserProfile[] = [
  {
    id: 'user-1',
    username: '@sofi',
    displayName: 'Sofía M.',
    avatar: 'https://i.pravatar.cc/150?img=11',
    languages: ['es', 'en'],
    city: 'Buenos Aires',
    barrio: 'Palermo',
    lastActiveAt: '2025-10-30T18:45:00.000Z',
    exchangesCompleted: 18,
    booksPublished: 12,
  },
  {
    id: 'user-2',
    username: '@marcos',
    displayName: 'Marcos R.',
    avatar: 'https://i.pravatar.cc/150?img=12',
    languages: ['es'],
    city: 'Buenos Aires',
    barrio: 'Chacarita',
    lastActiveAt: '2025-10-30T16:12:00.000Z',
    exchangesCompleted: 21,
    booksPublished: 9,
  },
  {
    id: 'user-3',
    username: '@lucia',
    displayName: 'Lucía F.',
    avatar: 'https://i.pravatar.cc/150?img=13',
    languages: ['es', 'fr'],
    city: 'Buenos Aires',
    barrio: 'Villa Crespo',
    lastActiveAt: '2025-10-28T22:05:00.000Z',
    exchangesCompleted: 9,
    booksPublished: 14,
  },
  {
    id: 'user-4',
    username: '@aylen',
    displayName: 'Aylén P.',
    avatar: 'https://i.pravatar.cc/150?img=14',
    languages: ['es', 'pt'],
    city: 'Buenos Aires',
    barrio: 'Caballito',
    lastActiveAt: '2025-10-26T11:40:00.000Z',
    exchangesCompleted: 15,
    booksPublished: 6,
  },
  {
    id: 'user-5',
    username: '@diego',
    displayName: 'Diego L.',
    avatar: 'https://i.pravatar.cc/150?img=15',
    languages: ['es', 'en'],
    city: 'Buenos Aires',
    barrio: 'Almagro',
    lastActiveAt: '2025-10-15T08:10:00.000Z',
    exchangesCompleted: 6,
    booksPublished: 4,
  },
  {
    id: 'user-6',
    username: '@valen',
    displayName: 'Valen C.',
    avatar: 'https://i.pravatar.cc/150?img=16',
    languages: ['es', 'en'],
    city: 'La Plata',
    barrio: 'Tolosa',
    lastActiveAt: '2025-09-29T19:33:00.000Z',
    exchangesCompleted: 4,
    booksPublished: 5,
  },
] as const;

export const COMMUNITY_CORNERS: readonly CommunityCorner[] = [
  {
    id: 'corner-1',
    name: 'Rincón Plaza Malabia',
    barrio: 'Palermo',
    city: 'Buenos Aires',
    active: true,
    map: { top: 42, left: 58 },
  },
  {
    id: 'corner-2',
    name: 'Bibliorincón Parque Patricios',
    barrio: 'Parque Patricios',
    city: 'Buenos Aires',
    active: true,
    map: { top: 68, left: 35 },
  },
  {
    id: 'corner-3',
    name: 'Club de Lectura Chacarita',
    barrio: 'Chacarita',
    city: 'Buenos Aires',
    active: true,
    map: { top: 51, left: 46 },
  },
  {
    id: 'corner-4',
    name: 'Rincón Barracas Sur',
    barrio: 'Barracas',
    city: 'Buenos Aires',
    active: false,
    map: { top: 79, left: 62 },
  },
  {
    id: 'corner-5',
    name: 'Punto de Lectura Villa Crespo',
    barrio: 'Villa Crespo',
    city: 'Buenos Aires',
    active: true,
    map: { top: 47, left: 41 },
  },
  {
    id: 'corner-6',
    name: 'Rincón Colegiales',
    barrio: 'Colegiales',
    city: 'Buenos Aires',
    active: true,
    map: { top: 44, left: 53 },
  },
] as const;

export const COMMUNITY_LISTINGS: readonly CommunityListing[] = [
  {
    id: 'listing-1',
    userId: 'user-1',
    cornerId: 'corner-1',
    title: 'Los años felices',
    author: 'Claudia Piñeiro',
    cover: 'https://picsum.photos/seed/anios-felices/600/400',
    category: 'book',
    likes: 42,
    createdAt: '2025-10-30T17:20:00.000Z',
    searchTags: ['fantasia juvenil', 'club de lectura', 'thriller'],
  },
  {
    id: 'listing-2',
    userId: 'user-2',
    cornerId: 'corner-2',
    title: 'La invención de la naturaleza',
    author: 'Andrea Wulf',
    cover: 'https://picsum.photos/seed/invencion-de-la-naturaleza/600/400',
    price: 12000,
    condition: 'como nuevo',
    category: 'sale',
    likes: 35,
    createdAt: '2025-10-30T15:00:00.000Z',
    searchTags: ['ensayo feminista', 'naturaleza', 'biografia'],
  },
  {
    id: 'listing-3',
    userId: 'user-3',
    cornerId: 'corner-5',
    title: 'Busco: Antología Poesía Mapuche',
    category: 'seeking',
    likes: 21,
    createdAt: '2025-10-29T20:10:00.000Z',
    searchTags: ['poesia contemporanea', 'traduccion', 'lenguas originarias'],
  },
  {
    id: 'listing-4',
    userId: 'user-4',
    cornerId: 'corner-3',
    title: 'El jardín secreto',
    author: 'Frances Hodgson Burnett',
    cover: 'https://picsum.photos/seed/jardin-secreto/600/400',
    category: 'book',
    likes: 29,
    createdAt: '2025-10-28T13:45:00.000Z',
    searchTags: ['infancias', 'aventura', 'clásicos'],
  },
  {
    id: 'listing-5',
    userId: 'user-1',
    cornerId: 'corner-1',
    title: 'Astroguía del Cono Sur',
    author: 'María Pía López',
    cover: 'https://picsum.photos/seed/astroguia-conosur/600/400',
    price: 6800,
    condition: 'usado',
    category: 'sale',
    likes: 18,
    createdAt: '2025-10-27T10:05:00.000Z',
    searchTags: ['astro', 'ensayo feminista', 'club de lectura'],
  },
  {
    id: 'listing-6',
    userId: 'user-2',
    cornerId: 'corner-6',
    title: 'Invasión 2040',
    author: 'Liliana Bodoc',
    cover: 'https://picsum.photos/seed/invasion-2040/600/400',
    category: 'book',
    likes: 24,
    createdAt: '2025-10-26T18:30:00.000Z',
    searchTags: [
      'ciencia ficcion argentina',
      'distopia latina',
      'fantasia juvenil',
    ],
  },
  {
    id: 'listing-7',
    userId: 'user-5',
    cornerId: null,
    title: 'Busco: Historias mínimas del AMBA',
    category: 'seeking',
    likes: 11,
    createdAt: '2025-10-25T09:15:00.000Z',
    searchTags: [
      'cronica urbana',
      'historia local',
      'ciencia ficcion argentina',
    ],
  },
  {
    id: 'listing-8',
    userId: 'user-3',
    cornerId: 'corner-5',
    title: 'Economías para el bien común',
    author: 'Christian Felber',
    cover: 'https://picsum.photos/seed/economias-del-bien-comun/600/400',
    price: 5400,
    condition: 'como nuevo',
    category: 'sale',
    likes: 16,
    createdAt: '2025-10-24T16:00:00.000Z',
    searchTags: ['economia solidaria', 'ensayo feminista', 'naturaleza'],
  },
  {
    id: 'listing-9',
    userId: 'user-4',
    cornerId: 'corner-3',
    title: 'La trama celeste',
    author: 'Adolfo Bioy Casares',
    cover: 'https://picsum.photos/seed/trama-celeste/600/400',
    category: 'book',
    likes: 14,
    createdAt: '2025-10-23T11:30:00.000Z',
    searchTags: ['ciencia ficcion argentina', 'clásicos', 'fantasia juvenil'],
  },
  {
    id: 'listing-10',
    userId: 'user-6',
    cornerId: 'corner-4',
    title: 'Crónicas del Río de la Plata',
    author: 'Eduardo Belgrano Rawson',
    cover: 'https://picsum.photos/seed/cronicas-del-rio-de-la-plata/600/400',
    category: 'book',
    likes: 9,
    createdAt: '2025-10-22T18:20:00.000Z',
    searchTags: ['historia local', 'cronica urbana'],
  },
] as const;

export const COMMUNITY_SWAPS: readonly CommunitySwap[] = [
  {
    id: 'swap-1',
    requesterId: 'user-3',
    responderId: 'user-1',
    offeredListingId: 'listing-8',
    requestedListingId: 'listing-1',
    cornerId: 'corner-5',
    likes: 17,
    createdAt: '2025-10-30T19:05:00.000Z',
  },
  {
    id: 'swap-2',
    requesterId: 'user-4',
    responderId: 'user-2',
    offeredListingId: 'listing-9',
    requestedListingId: 'listing-2',
    cornerId: 'corner-3',
    likes: 23,
    createdAt: '2025-10-29T21:45:00.000Z',
  },
  {
    id: 'swap-3',
    requesterId: 'user-1',
    responderId: 'user-2',
    offeredListingId: 'listing-5',
    requestedListingId: 'listing-6',
    cornerId: 'corner-1',
    likes: 31,
    createdAt: '2025-10-27T12:35:00.000Z',
  },
] as const;

export const POPULAR_SEARCH_SEED: ReadonlyArray<{
  term: string;
  weight: number;
}> = [
  { term: 'ensayo feminista', weight: 2 },
  { term: 'fantasia juvenil', weight: 1 },
  { term: 'ciencia ficcion argentina', weight: 0 },
  { term: 'club de lectura', weight: 1 },
  { term: 'historia local', weight: 0 },
];

export const TREND_EXCHANGES = [36, 42, 45, 51, 58, 64, 72] as const;
export const TREND_NEW_BOOKS = [18, 21, 24, 22, 27, 29, 33] as const;
