name: Backend Docker

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/backend-docker.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/backend-docker.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build backend Docker image
        run: docker build -f backend/Dockerfile .
