name: Dependabot auto-merge
on: pull_request_target

permissions:
  contents: write
  pull-requests: write
  checks: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@d7267f607e9d3fb96fc2fbe83e0af444713e90b7
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Approve PR
        if: contains(steps.metadata.outputs.dependency-names, 'my-dependency')
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}

      - name: Enable auto-merge
        if: contains(steps.metadata.outputs.dependency-names, 'my-dependency')
        run: |
          gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}