name: Deploy to staging

on:
  push:
    branches:
      - main

jobs:
  staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
    services:
      postgres:
        image: postgis/postgis:16-3.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: entrelibros_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      CI: true
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/entrelibros_test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Prepare image names
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          if [[ -z "${DOCKERHUB_USERNAME}" ]]; then
            echo "ERROR: Set the DOCKERHUB_USERNAME secret to publish Docker images." >&2
            exit 1
          fi
          echo "BACKEND_IMAGE=docker.io/${DOCKERHUB_USERNAME}/entrelibros-backend" >> "$GITHUB_ENV"
          echo "FRONTEND_IMAGE=docker.io/${DOCKERHUB_USERNAME}/entrelibros-frontend" >> "$GITHUB_ENV"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        id: build-backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:${{ github.sha }}
          provenance: false

      - name: Build and push frontend image
        id: build-frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}:${{ github.sha }}
          provenance: false

      - name: Record image digests
        id: record-digests
        run: |
          cat <<JSON > staging-digests.json
          {
            "backend": {
              "image": "${{ env.BACKEND_IMAGE }}",
              "tag": "${{ github.sha }}",
              "digest": "${{ steps.build-backend.outputs.digest }}"
            },
            "frontend": {
              "image": "${{ env.FRONTEND_IMAGE }}",
              "tag": "${{ github.sha }}",
              "digest": "${{ steps.build-frontend.outputs.digest }}"
            }
          }
          JSON
          cat staging-digests.json

      - name: Upload staging digests
        uses: actions/upload-artifact@v4
        with:
          name: staging-digests
          path: staging-digests.json

      - name: Deploy to staging
        env:
          BACKEND_REFERENCE: ${{ env.BACKEND_IMAGE }}@${{ steps.build-backend.outputs.digest }}
          FRONTEND_REFERENCE: ${{ env.FRONTEND_IMAGE }}@${{ steps.build-frontend.outputs.digest }}
        run: |
          echo "Deploying ${BACKEND_REFERENCE} to staging"
          echo "Deploying ${FRONTEND_REFERENCE} to staging"
          if [[ -x "./scripts/deploy-staging.sh" ]]; then
            ./scripts/deploy-staging.sh "$BACKEND_REFERENCE" "$FRONTEND_REFERENCE"
          else
            echo "ERROR: Deployment commands are not configured. Provide scripts/deploy-staging.sh to perform the rollout." >&2
            exit 1
          fi

      - name: Run smoke tests
        env:
          BACKEND_REFERENCE: ${{ env.BACKEND_IMAGE }}@${{ steps.build-backend.outputs.digest }}
          FRONTEND_REFERENCE: ${{ env.FRONTEND_IMAGE }}@${{ steps.build-frontend.outputs.digest }}
        run: |
          ./scripts/run-smoke-tests.sh "$BACKEND_REFERENCE" "$FRONTEND_REFERENCE"
